import type { OpsConfig } from "@/lib/ops-types";

export const OPS_CONFIG_STORAGE_KEY = "sovereign-observer.ops-config";

export function createDefaultOpsConfig(): OpsConfig {
  return {
    zones: [
      {
        id: "gulf-coast",
        name: "Gulf Coast",
        regionKeywords: ["texas", "louisiana", "mississippi", "alabama", "florida"],
        countryCodes: ["US"],
        eventFamilies: ["storm", "flood", "hurricane", "cyclone"],
        staffingPoolIds: ["cat-command", "field-adjusters"],
        routingDestinationIds: ["slack-cat-ops", "queue-field-ops"],
      },
      {
        id: "atlantic-seaboard",
        name: "Atlantic Seaboard",
        regionKeywords: ["georgia", "carolina", "virginia", "maryland", "new york"],
        countryCodes: ["US"],
        eventFamilies: ["storm", "flood", "hurricane", "cyclone"],
        staffingPoolIds: ["cat-command", "claims-surge"],
        routingDestinationIds: ["slack-cat-ops", "queue-claims-intake"],
      },
      {
        id: "western-fireline",
        name: "Western Fireline",
        regionKeywords: ["california", "oregon", "washington", "nevada", "arizona"],
        countryCodes: ["US"],
        eventFamilies: ["wildfire", "heat", "storm"],
        staffingPoolIds: ["field-adjusters", "vendor-network"],
        routingDestinationIds: ["queue-field-ops", "email-vendor-network"],
      },
      {
        id: "inland-flood-belt",
        name: "Inland Flood Belt",
        regionKeywords: ["missouri", "illinois", "iowa", "kansas", "nebraska", "oklahoma"],
        countryCodes: ["US"],
        eventFamilies: ["flood", "storm", "tornado"],
        staffingPoolIds: ["claims-surge", "vendor-network"],
        routingDestinationIds: ["queue-claims-intake", "email-vendor-network"],
      },
    ],
    staffingPools: [
      {
        id: "cat-command",
        name: "CAT Command",
        team: "Operations leadership",
        activeAgents: 8,
        reserveAgents: 4,
        concurrentCapacity: 24,
        supportedEventFamilies: ["storm", "flood", "hurricane", "cyclone", "wildfire"],
        zoneIds: ["gulf-coast", "atlantic-seaboard"],
      },
      {
        id: "claims-surge",
        name: "Claims Surge Desk",
        team: "Claims intake",
        activeAgents: 24,
        reserveAgents: 10,
        concurrentCapacity: 120,
        supportedEventFamilies: ["storm", "flood", "tornado", "hail"],
        zoneIds: ["atlantic-seaboard", "inland-flood-belt"],
      },
      {
        id: "field-adjusters",
        name: "Field Adjusters",
        team: "Field response",
        activeAgents: 18,
        reserveAgents: 12,
        concurrentCapacity: 72,
        supportedEventFamilies: ["wildfire", "storm", "hurricane", "flood"],
        zoneIds: ["gulf-coast", "western-fireline"],
      },
      {
        id: "vendor-network",
        name: "Vendor Network",
        team: "Partner operations",
        activeAgents: 12,
        reserveAgents: 8,
        concurrentCapacity: 48,
        supportedEventFamilies: ["wildfire", "flood", "storm", "tornado"],
        zoneIds: ["western-fireline", "inland-flood-belt"],
      },
    ],
    routingDestinations: [
      {
        id: "slack-cat-ops",
        name: "CAT Ops Slack",
        channel: "slack",
        target: "#cat-ops",
        enabled: true,
        priority: 1,
        zoneIds: ["gulf-coast", "atlantic-seaboard"],
        eventFamilies: ["storm", "flood", "hurricane", "cyclone"],
        alertLevels: ["medium", "high", "critical"],
      },
      {
        id: "queue-claims-intake",
        name: "Claims Intake Queue",
        channel: "queue",
        target: "claims-intake-priority",
        enabled: true,
        priority: 2,
        zoneIds: ["atlantic-seaboard", "inland-flood-belt"],
        eventFamilies: ["storm", "flood", "tornado", "hail"],
        alertLevels: ["low", "medium", "high", "critical"],
      },
      {
        id: "queue-field-ops",
        name: "Field Ops Queue",
        channel: "queue",
        target: "field-ops-dispatch",
        enabled: true,
        priority: 1,
        zoneIds: ["gulf-coast", "western-fireline"],
        eventFamilies: ["wildfire", "storm", "hurricane", "flood"],
        alertLevels: ["medium", "high", "critical"],
      },
      {
        id: "email-vendor-network",
        name: "Vendor Network Email",
        channel: "email",
        target: "partners@sovereignobserver.demo",
        enabled: true,
        priority: 3,
        zoneIds: ["western-fireline", "inland-flood-belt"],
        eventFamilies: ["wildfire", "flood", "storm", "tornado"],
        alertLevels: ["high", "critical"],
      },
    ],
    thresholds: {
      readinessWarningScore: 70,
      readinessCriticalScore: 45,
      maxAlertLoadPerCoordinator: 3,
      maxClaimsLoadPerAgent: 8,
      staleSourceMinutes: 120,
      quietSourceMinutes: 45,
    },
  };
}

export const DEFAULT_OPS_CONFIG = createDefaultOpsConfig();
