import type { OpsConfig } from "@/lib/ops-types";

export const OPS_CONFIG_STORAGE_KEY = "sovereign-observer.ops-config";

export function createDefaultOpsConfig(): OpsConfig {
  return {
    zones: [
      {
        id: "asia-pacific",
        name: "Asia Pacific",
        regionKeywords: ["japan", "china", "philippines", "papua", "australia", "indonesia", "taiwan"],
        countryCodes: ["JPN", "CHN", "PHL", "PNG", "AUS", "IDN", "TWN"],
        eventFamilies: ["natural", "earthquake", "cyclone", "flood", "storm", "tsunami", "wildfire"],
        staffingPoolIds: ["cat-command", "field-adjusters"],
        routingDestinationIds: ["slack-cat-ops", "queue-field-ops"],
      },
      {
        id: "europe",
        name: "Europe",
        regionKeywords: ["france", "germany", "spain", "italy", "uk", "poland", "netherlands"],
        countryCodes: ["FRA", "DEU", "ESP", "ITA", "GBR", "POL", "NLD"],
        eventFamilies: ["natural", "flood", "storm", "wildfire", "earthquake"],
        staffingPoolIds: ["claims-surge", "cat-command"],
        routingDestinationIds: ["queue-claims-intake", "slack-cat-ops"],
      },
      {
        id: "americas",
        name: "Americas",
        regionKeywords: ["costa rica", "brazil", "mexico", "chile", "colombia", "peru", "argentina"],
        countryCodes: ["CRI", "BRA", "MEX", "CHL", "COL", "PER", "ARG", "VEN", "USA"],
        eventFamilies: ["natural", "earthquake", "flood", "storm", "cyclone", "wildfire"],
        staffingPoolIds: ["field-adjusters", "vendor-network"],
        routingDestinationIds: ["queue-field-ops", "email-vendor-network"],
      },
      {
        id: "global-cat",
        name: "Global CAT",
        regionKeywords: [],
        countryCodes: [],
        eventFamilies: ["natural", "earthquake", "cyclone", "tsunami", "wildfire", "flood", "storm"],
        staffingPoolIds: ["cat-command", "claims-surge"],
        routingDestinationIds: ["slack-cat-ops", "queue-claims-intake"],
      },
    ],
    staffingPools: [
      {
        id: "cat-command",
        name: "CAT Command",
        team: "Operations leadership",
        activeAgents: 8,
        reserveAgents: 4,
        concurrentCapacity: 24,
        supportedEventFamilies: ["natural", "earthquake", "cyclone", "tsunami", "wildfire", "flood", "storm"],
        zoneIds: ["asia-pacific", "global-cat"],
      },
      {
        id: "claims-surge",
        name: "Claims Surge Desk",
        team: "Claims intake",
        activeAgents: 24,
        reserveAgents: 10,
        concurrentCapacity: 120,
        supportedEventFamilies: ["natural", "flood", "storm", "earthquake", "wildfire"],
        zoneIds: ["europe", "global-cat"],
      },
      {
        id: "field-adjusters",
        name: "Field Adjusters",
        team: "Field response",
        activeAgents: 18,
        reserveAgents: 12,
        concurrentCapacity: 72,
        supportedEventFamilies: ["natural", "wildfire", "storm", "flood", "earthquake"],
        zoneIds: ["asia-pacific", "americas"],
      },
      {
        id: "vendor-network",
        name: "Vendor Network",
        team: "Partner operations",
        activeAgents: 12,
        reserveAgents: 8,
        concurrentCapacity: 48,
        supportedEventFamilies: ["natural", "flood", "storm", "earthquake", "wildfire", "cyclone"],
        zoneIds: ["americas", "europe"],
      },
    ],
    routingDestinations: [
      {
        id: "slack-cat-ops",
        name: "CAT Ops Slack",
        channel: "slack",
        target: "#cat-ops",
        enabled: true,
        priority: 1,
        zoneIds: ["asia-pacific", "global-cat"],
        eventFamilies: ["natural", "earthquake", "cyclone", "tsunami", "wildfire", "flood"],
        alertLevels: ["low", "medium", "high", "critical"],
      },
      {
        id: "queue-claims-intake",
        name: "Claims Intake Queue",
        channel: "queue",
        target: "claims-intake-priority",
        enabled: true,
        priority: 2,
        zoneIds: ["europe", "global-cat"],
        eventFamilies: ["natural", "flood", "storm", "earthquake", "wildfire"],
        alertLevels: ["low", "medium", "high", "critical"],
      },
      {
        id: "queue-field-ops",
        name: "Field Ops Queue",
        channel: "queue",
        target: "field-ops-dispatch",
        enabled: true,
        priority: 1,
        zoneIds: ["asia-pacific", "americas"],
        eventFamilies: ["natural", "wildfire", "earthquake", "flood", "storm"],
        alertLevels: ["low", "medium", "high", "critical"],
      },
      {
        id: "email-vendor-network",
        name: "Vendor Network Email",
        channel: "email",
        target: "partners@sovereignobserver.demo",
        enabled: true,
        priority: 3,
        zoneIds: ["americas", "europe"],
        eventFamilies: ["natural", "flood", "storm", "earthquake", "wildfire"],
        alertLevels: ["low", "medium", "high", "critical"],
      },
    ],
    thresholds: {
      readinessWarningScore: 70,
      readinessCriticalScore: 45,
      maxAlertLoadPerCoordinator: 3,
      maxClaimsLoadPerAgent: 8,
      staleSourceMinutes: 120,
      quietSourceMinutes: 45,
    },
  };
}

export const DEFAULT_OPS_CONFIG = createDefaultOpsConfig();
